input: ./input.jar
output: ./output.jar
libs:
  - ./libs
annotationMode: true
includes:
  -
excludes:
  -
obfuscation:
  stringEncryption: false
  flowObfuscation: true
  antiDebug: true
  ir: true
  lifterResistance: true
optimization:
  ir: true
